language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - rbx-19mode
  - jruby-19mode
  - jruby-20mode
branches:
  only:
    - master
before_install:
  - sudo apt-get install subversion
  - git submodule update --init --recursive
  - echo "yes" | gem uninstall ffi -a
before_script:
  - rake libuv
